title: GPT3 Prompts
description: A free Course and Playbook for ChatGPT3 Prompt Engineering
baseurl: "/pages" # the subpath of your site, e.g. /blog

theme: just-the-docs

color_scheme: dark
heading_anchors: true
search_enabled: true

url: https://mattnigh.github.io/ChatGPT3-Prompt-Engineering

aux_links:
  Template Repository: https://github.com/mattnigh/ChatGPT3-Prompt-Engineering

exclude:
 # from https://github.com/mattnigh/ChatGPT3-Prompt-Engineering/_config.yml:
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - LICENSE.txt
   - README.md
